language: go
go:
- 1.9
- tip
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
before_script: 
script:
- glide install
- go build -o loom-linux-x64-$TRAVIS_TAG .
deploy:
  provider: releases
  api_key:
    secure: NNb/vu3NGEC93dmyo/J6tpN86vh6XpQWjKGZtIlYRa1CmasHb/1C+sWtfUWV804PIwLkkOiC/yIdfCqOhWSmNYIuIgqvnZMPI8Kuw6NI4qyq2Q1eUhV1ETqYaA3CDxsn+IzCoaSVGgUKm6+ODsYKsVXmLKZOPwggxC1RGGnS8pH2kJjMeouTPZgopl47VVFi4QM70yOF9rNKP1GFQhuoScG+zQZe5PuvYtpBCsIQ3sbW8j97khkSDEEsRPC9l6vK2PVgNH3SYkBDeoQaWkthQOLY+ZHOEhgVHtK19P0ZWWWSjqn2xg5WxPFE8qnMVfPEwsgAMS5Avf6RXTivGMcPyhJ1JayDNYuMIUF6LbBJ/JShWX5800Y2biKLkXfX8U21gvxC81aovaXOBdXsYPHAjIgER1ZJDcManEcgsz0N/jMFlDqRvAo1sN4sMNK/XH4abR8BxqmQt7/8SWEs6HEmd6LSF3MgeoTr93Io0kKVOZgwhO68BlqEwNmbs+bFRXsNVFkD/EETGSfPIM2G5BGx1wxfazGtSK/J3VTfhP6kqJPqx/je45QF9lAR4yrKVzEqFnnvATKT/LaeFXQCP7Z0vOLZItY7qRg1XG3yl/iFGUspcMZAVghuKKfKxGd8AOL0RO52Xty71e/zLNMNDDf3D/zmyyuB4NeGRvA1OkQFkho=
  file:  target/loom-linux-x64-$TRAVIS_TAG
  on:
    tags: true